Repository wafflestudio/guam_front, pull requests merged in 2021-06, with the labels that each got.

#21 Fix/검색 페이지 수정
  lib/screens/projects/search/project_search.dart
  lib/screens/projects/search/project_search_filter.dart
Labels: enhancement

#19 Fix/프로젝트 세부 페이지 디자인 변경
  lib/providers/projects/projects.dart
  lib/screens/projects/detail/project_apply.dart
  lib/screens/projects/detail/project_detail.dart
  lib/screens/projects/detail/project_detail_body.dart
  lib/screens/projects/project_apply.dart
  lib/screens/projects/project_banner.dart
  lib/screens/projects/project_detail.dart
  lib/screens/projects/project_square.dart
  lib/screens/projects/search/project_search_form.dart
Labels: enhancement

#17 Feature/프로젝트 생성 페이지
  lib/commons/page_status.dart
  lib/commons/project_create_container.dart
  lib/screens/projects/creation/create_filter_chip.dart
  lib/screens/projects/creation/create_filter_value_chip.dart
  lib/screens/projects/creation/project_create.dart
  lib/screens/projects/projects_app.dart
  lib/screens/projects/search/search_filter_chip.dart
Labels: feature

#24 Boards 디자인 및 기능 완성
  assets/backgrounds/boards-bg.png
  assets/backgrounds/projects-bg.png
  assets/backgrounds/thread-page-bg.png
  lib/commons/circular_border_container.dart
  lib/commons/grey_container.dart
  lib/commons/profile_thumbnail.dart
  lib/commons/thread_text_field.dart
  lib/models/boards/comment.dart
  lib/models/boards/thread.dart
  lib/providers/boards/boards.dart
  lib/screens/boards/board.dart
  lib/screens/boards/boards_app.dart
  lib/screens/boards/comment.dart
  lib/screens/boards/iconTitle.dart
  lib/screens/boards/notice.dart
  lib/screens/boards/progress.dart
  lib/screens/boards/progresses.dart
  lib/screens/boards/thread.dart
  lib/screens/boards/thread_page.dart
  lib/screens/boards/threads.dart
Labels: feature

#26 Fix/provider
  lib/helpers/decode_ko.dart
  lib/models/project.dart
  lib/providers/projects/projects.dart
  lib/providers/user_auth/authenticate.dart
  lib/screens/projects/almost_full_projects_list.dart
  lib/screens/projects/projects_app.dart
  lib/screens/projects/projects_list.dart
Labels: enhancement

#29 Fetch stacks
  lib/main.dart
  lib/models/stack.dart
  lib/providers/stacks/stacks.dart
Labels: server
