Repository wafflestudio/guam_front, pull requests merged in 2021-05, with the labels that each got.

#7 feature/프로필 탭 디자인
  android/app/src/main/AndroidManifest.xml
  ios/Podfile
  ios/Podfile.lock
  ios/Runner.xcodeproj/project.pbxproj
  ios/Runner/GoogleService-Info.plist
  ios/Runner/Info.plist
  lib/screens/my_page/my_page.dart
  lib/screens/my_page/my_page_body.dart
  pubspec.lock
  pubspec.yaml
Labels: feature

#8 feature/프로젝트 세부 페이지
  lib/commons/app_bar.dart
  lib/commons/back.dart
  lib/models/project.dart
  lib/providers/projects/projects.dart
  lib/screens/my_page/my_page.dart
  lib/screens/projects/project_banner.dart
  lib/screens/projects/project_detail.dart
  lib/screens/projects/project_square.dart
Labels: feature

#13 feature/프로젝트 세부 페이지 수정
  lib/screens/projects/project_apply.dart
  lib/screens/projects/project_detail.dart
  pubspec.lock
  pubspec.yaml
Labels: enhancement

#10 feature/검색 페이지
  lib/screens/projects/projects_app.dart
  lib/screens/projects/search/filter_value_chip.dart
  lib/screens/projects/search/project_search.dart
  lib/screens/projects/search/project_search_filter.dart
  lib/screens/projects/search/project_search_form.dart
  lib/screens/projects/search/search_filter_chip.dart
  pubspec.lock
Labels: feature

#14 Feat/kakao login
  android/app/build.gradle
  android/app/src/debug/AndroidManifest.xml
  android/app/src/main/AndroidManifest.xml
  android/app/src/main/kotlin/com/wafflestudio/guam/MainActivity.kt
  android/app/src/profile/AndroidManifest.xml
  android/build.gradle
  android/gradle/wrapper/gradle-wrapper.properties
  assets/buttons/kakao_login_medium_narrow.png
  ios/Podfile
  ios/Podfile.lock
  ios/Runner.xcodeproj/project.pbxproj
  ios/Runner/Info.plist
  lib/commons/app_bar.dart
  lib/main.dart
  lib/providers/user_auth/authenticate.dart
  lib/screens/home/root.dart
  lib/screens/my_page/my_page.dart
  lib/screens/user_auth/auth.dart
  lib/screens/user_auth/kakao_login.dart
  pubspec.lock
  pubspec.yaml
Labels: Firebase

#16 User Axios & Initialization Done.
  ios/Podfile.lock
  lib/commons/profile_thumbnail.dart
  lib/helpers/http_request.dart
  lib/models/profile.dart
  lib/providers/boards/boards.dart
  lib/providers/projects/projects.dart
  lib/providers/user_auth/authenticate.dart
  lib/screens/boards/boards_app.dart
  lib/screens/my_page/make_profile_page.dart
  lib/screens/my_page/my_page.dart
  lib/screens/my_page/my_profile.dart
  lib/screens/projects/projects_app.dart
  lib/screens/projects/search/project_search_filter.dart
  lib/screens/user_auth/auth.dart
  lib/screens/user_auth/kakao_login.dart
  lib/screens/user_auth/sign_in.dart
  lib/screens/user_auth/sign_out.dart
  lib/screens/user_auth/sign_up.dart
Labels: Firebase
