Repository wafflestudio/guam_front, pull requests merged in 2021-08, with the labels that each got.

#50 TASK: create + edit status
  lib/commons/common_text_field.dart
  lib/models/boards/task_msg.dart
  lib/models/boards/user_task.dart
  lib/models/project.dart
  lib/providers/boards/boards.dart
  lib/screens/boards/board.dart
  lib/screens/boards/notice/notice.dart
  lib/screens/boards/task.dart
  lib/screens/boards/tasks/empty_task_message.dart
  lib/screens/boards/tasks/task.dart
  lib/screens/boards/tasks/task_message.dart
  lib/screens/boards/tasks/tasks.dart
  lib/screens/boards/threads/thread.dart
  lib/screens/boards/threads/threads.dart
Labels: feature

#52 Fix/project search
  lib/providers/projects/projects.dart
  lib/screens/projects/projects_app.dart
  lib/screens/projects/search/project_search.dart
  lib/screens/projects/search/project_search_button.dart
  lib/screens/projects/search/project_search_form.dart
  lib/screens/projects/search/projects_searched_list.dart
  lib/screens/projects/search/search_filter_chip.dart
Labels: enhancement, server

#54 fix problem of initializing skills (updating a profile) / title & description (creating a project)
  lib/screens/my_page/make_profile_page.dart
  lib/screens/projects/creation/page_one/project_create_description.dart
  lib/screens/projects/creation/page_one/project_create_title.dart
Labels: enhancement

#60 쓰레드 로드모어
  lib/providers/boards/boards.dart
  lib/screens/boards/threads/threads.dart
Labels: feature

#63 Bug Report Mailer
  lib/commons/buttons/common_outlined_button.dart
  lib/mixins/toast.dart
  lib/screens/my_page/my_profile/button_report.dart
  lib/screens/my_page/my_profile/modal_report.dart
  lib/screens/my_page/my_profile/my_profile.dart
  lib/screens/user_auth/sign_out.dart
  pubspec.lock
  pubspec.yaml
Labels: feature

#66 Feature/project edit
  lib/providers/boards/boards.dart
  lib/providers/projects/projects.dart
  lib/screens/boards/board_setting.dart
  lib/screens/boards/boards_app.dart
  lib/screens/boards/quit_board.dart
  lib/screens/projects/creation/page_one/project_create_due.dart
  lib/screens/projects/creation/page_three/project_create_page_three.dart
  lib/screens/projects/creation/page_three/project_create_save.dart
  lib/screens/projects/creation/page_three/project_create_thumbnail.dart
  lib/screens/projects/creation/project_create.dart
  lib/screens/projects/creation/project_create_button.dart
  lib/screens/projects/creation/project_edit.dart
Labels: feature, server

#61 show confirmed message when deleting something
  lib/commons/bottom_modal/bottom_modal_content.dart
  lib/commons/bottom_modal/function_container.dart
  lib/screens/boards/board_setting.dart
  lib/screens/boards/thread_page/comment.dart
  lib/screens/boards/threads/thread.dart
Labels: enhancement

#57 Feature/another profile
  lib/commons/profile_thumbnail.dart
  lib/providers/user_auth/authenticate.dart
  lib/screens/boards/notice/notice.dart
  lib/screens/boards/tasks/tasks.dart
  lib/screens/boards/thread_page/comment.dart
  lib/screens/boards/thread_page/thread_container.dart
  lib/screens/boards/threads/thread.dart
  lib/screens/my_page/another_profile/another_profile.dart
  lib/screens/my_page/another_profile/another_profile_app.dart
  lib/screens/my_page/make_profile_page.dart
  lib/screens/my_page/my_page_app.dart
  lib/screens/my_page/my_profile/my_profile.dart
  lib/screens/profiles/profile_bottom.dart
  lib/screens/profiles/profile_filter_value_chip.dart
  lib/screens/profiles/profile_link.dart
  lib/screens/profiles/profile_projects.dart
  lib/screens/profiles/profile_top.dart
  lib/screens/projects/detail/project_detail.dart
  lib/screens/projects/project_banner.dart
  lib/screens/projects/project_square.dart
Labels: feature, server

#64 Design/splash and logo
  assets/backgrounds/splash-bg.png
  assets/fonts/Poppins-SemiBold.ttf
  lib/screens/home/guam_text.dart
  lib/screens/home/splash.dart
  lib/screens/user_auth/auth.dart
  pubspec.yaml
Labels: feature

#71 QA / text
  lib/commons/common_text_field.dart
  lib/screens/my_page/make_profile_page.dart
  lib/screens/projects/creation/page_one/project_create_description.dart
  lib/screens/projects/creation/page_one/project_create_title.dart
Labels: enhancement

#70 fix the error rendering the number of project members
  lib/screens/projects/project_banner.dart
  lib/screens/projects/project_square.dart
Labels: enhancement

#72 Feat/push notification
  android/app/src/main/AndroidManifest.xml
  android/app/src/main/res/drawable/push_icon.png
  lib/main.dart
  lib/providers/user_auth/authenticate.dart
  lib/screens/user_auth/auth.dart
  pubspec.lock
  pubspec.yaml
Labels: Firebase

#76 Toast failure event handling
  lib/commons/images_carousel_page.dart
  lib/helpers/http_request.dart
  lib/providers/boards/boards.dart
  lib/providers/projects/projects.dart
  lib/providers/stacks/stacks.dart
  lib/providers/user_auth/authenticate.dart
Labels: bug

#75 Fix/project stack align
  lib/screens/projects/creation/page_two/project_create_positions.dart
  lib/screens/projects/creation/page_two/project_create_selected_positions.dart
  lib/screens/projects/detail/project_detail_apply.dart
  lib/screens/projects/detail/project_detail_body.dart
Labels: enhancement

#78 Fix/project title length and logout edit
  lib/screens/my_page/my_page_app.dart
  lib/screens/projects/creation/page_one/project_create_title.dart
Labels: enhancement

#84 Fix/profile
  lib/screens/my_page/make_profile_image.dart
  lib/screens/my_page/my_profile/my_profile.dart
  lib/screens/profiles/profile_link.dart
Labels: enhancement

#86 알파 1.0.1 버전
  android/app/src/main/AndroidManifest.xml
  lib/commons/profile_thumbnail.dart
  lib/providers/projects/projects.dart
  lib/providers/user_auth/authenticate.dart
  lib/screens/boards/notice/notice.dart
  lib/screens/boards/tasks/tasks.dart
  lib/screens/boards/thread_page/comment.dart
  lib/screens/boards/thread_page/thread_container.dart
  lib/screens/boards/threads/thread.dart
  lib/screens/projects/creation/page_two/project_create_page_two.dart
  lib/screens/projects/creation/page_two/project_create_positions.dart
  lib/screens/projects/detail/apply_button.dart
  lib/screens/projects/detail/project_detail.dart
  lib/screens/projects/detail/project_detail_apply.dart
  lib/screens/projects/detail/project_detail_body.dart
  lib/screens/projects/project_banner.dart
  lib/screens/projects/project_square.dart
Labels: enhancement

#90 ver. 1.0.2 - KO
  lib/screens/my_page/make_profile_page.dart
  lib/screens/projects/creation/page_one/project_create_due.dart
  lib/screens/projects/creation/page_three/project_create_my_position.dart
Labels: enhancement

#91 Fix / board title
  lib/commons/scrolling_text.dart
  lib/screens/boards/board_setting.dart
  lib/screens/boards/board_title/expanded_title_container.dart
Labels: enhancement

#89 ver 1.0.2 - ryu
  assets/buttons/kakao_login_large_narrow.png
  ios/Podfile.lock
  lib/commons/common_sizes.dart
  lib/providers/boards/boards.dart
  lib/providers/user_auth/authenticate.dart
  lib/screens/boards/board_title/board_title.dart
  lib/screens/boards/board_title/expanded_title_container.dart
  lib/screens/boards/threads/fold_threads_button.dart
  lib/screens/boards/threads/threads.dart
  lib/screens/user_auth/kakao_login.dart
Labels: enhancement

#94 ver. 1.0.3 - KO
  lib/commons/bottom_modal/bottom_modal_content.dart
  lib/providers/boards/boards.dart
  lib/screens/boards/board_setting.dart
  lib/screens/boards/thread_page/comment.dart
  lib/screens/boards/threads/thread.dart
Labels: feature, server
