Repository wafflestudio/guam_front, pull requests merged in 2021-09, with the labels that each got.

#100 Real domain으로 refactoring 브랜치 baseUrl 전환 및 http 관련 코드 삭제
  android/app/src/main/AndroidManifest.xml
  ios/Runner/Info.plist
  lib/helpers/http_request.dart
Labels: feature

#99 1.0.4 - ryu
  assets/images/boards_placeholder.png
  lib/commons/common_sizes.dart
  lib/models/boards/comment.dart
  lib/models/boards/thread.dart
  lib/providers/boards/boards.dart
  lib/screens/boards/board.dart
  lib/screens/boards/boards_app.dart
  lib/screens/boards/boards_body.dart
  lib/screens/boards/boards_placeholder.dart
  lib/screens/boards/thread_page/comment.dart
  lib/screens/boards/thread_page/thread_container.dart
  lib/screens/boards/threads/thread.dart
  lib/screens/boards/threads/threads.dart
  lib/screens/my_page/make_profile_page.dart
Labels: feature

#101 Fix/1.0.4 ko
  lib/providers/projects/projects.dart
  lib/screens/projects/project_banner.dart
  lib/screens/projects/project_square.dart
  lib/screens/projects/projects_body.dart
  lib/screens/projects/search/project_search_form.dart
  lib/screens/projects/search/projects_searched_list.dart
Labels: bug, enhancement

#104 Tutorial 등장 조건 code 추가
  lib/screens/home/home.dart
  lib/screens/projects/almost_full_projects_list.dart
  lib/screens/projects/project_square.dart
  lib/screens/projects/projects_app.dart
  lib/screens/projects/projects_body.dart
  lib/screens/projects/projects_list.dart
Labels: feature

#103 Feature/tutorial
  assets/tutorial/tutorial_bg_1.png
  assets/tutorial/tutorial_bg_2.png
  assets/tutorial/tutorial_board.png
  assets/tutorial/tutorial_profile_tab.png
  assets/tutorial/tutorial_project_create.png
  assets/tutorial/tutorial_project_search.png
  assets/tutorial/tutorial_project_tab.png
  assets/tutorial/tutorial_thread.png
  lib/commons/arrow_button.dart
  lib/commons/bottom_modal/function_container.dart
  lib/commons/common_confirm_dialog.dart
  lib/commons/page_status.dart
  lib/screens/home/home.dart
  lib/screens/projects/almost_full_projects_list.dart
  lib/screens/projects/creation/project_create.dart
  lib/screens/projects/creation/project_edit.dart
  lib/screens/projects/project_square.dart
  lib/screens/projects/projects_app.dart
  lib/screens/projects/projects_body.dart
  lib/screens/projects/projects_list.dart
  lib/screens/tutorial/exit_tutorial_button.dart
  lib/screens/tutorial/tutorial_image.dart
  lib/screens/tutorial/tutorial_modal.dart
  lib/screens/tutorial/tutorial_page.dart
  pubspec.yaml
Labels: feature

#109 change file size of tutorial images
  assets/tutorial/tutorial_bg_1.png
  assets/tutorial/tutorial_bg_2.png
  assets/tutorial/tutorial_board.png
  assets/tutorial/tutorial_profile_tab.png
  assets/tutorial/tutorial_project_create.png
  assets/tutorial/tutorial_project_search.png
  assets/tutorial/tutorial_project_tab.png
  assets/tutorial/tutorial_thread.png
Labels: enhancement

#114 일단은 팁 주석처리함
  lib/screens/projects/search/projects_searched_list.dart
Labels: bug

#118 Fix/1.0.6+ : fix tutorial page
  assets/tutorial/tutorial-1.png
  assets/tutorial/tutorial-2.png
  assets/tutorial/tutorial-3.png
  assets/tutorial/tutorial-4.png
  assets/tutorial/tutorial-5.png
  assets/tutorial/tutorial-6.png
  assets/tutorial/tutorial_bg_1.png
  assets/tutorial/tutorial_bg_2.png
  assets/tutorial/tutorial_board.png
  assets/tutorial/tutorial_profile_tab.png
  assets/tutorial/tutorial_project_create.png
  assets/tutorial/tutorial_project_search.png
  assets/tutorial/tutorial_project_tab.png
  assets/tutorial/tutorial_thread.png
  lib/screens/boards/accept_decline_button.dart
  lib/screens/tutorial/tutorial_image.dart
  lib/screens/tutorial/tutorial_modal.dart
  lib/screens/tutorial/tutorial_page.dart
Labels: enhancement
