Repository wafflestudio/guam_front, pull requests merged in 2021-07, with the labels that each got.

#30 Server/project search
  android/app/src/main/AndroidManifest.xml
  ios/Runner/Info.plist
  lib/providers/projects/projects.dart
  lib/screens/projects/projects_app.dart
  lib/screens/projects/search/project_search.dart
  lib/screens/projects/search/project_search_button.dart
  lib/screens/projects/search/project_search_filter.dart
  lib/screens/projects/search/project_search_form.dart
  lib/screens/projects/search/projects_searched_list.dart
Labels: server

#34 작업실 서버 코드 부착 및 리팩토링
  lib/commons/common_text_field.dart
  lib/commons/profile_thumbnail.dart
  lib/commons/thread_text_field.dart
  lib/models/boards/comment.dart
  lib/models/boards/thread.dart
  lib/models/boards/user_progress.dart
  lib/models/boards/user_task.dart
  lib/models/profile.dart
  lib/models/project.dart
  lib/providers/boards/boards.dart
  lib/providers/user_auth/authenticate.dart
  lib/screens/boards/board.dart
  lib/screens/boards/board_title.dart
  lib/screens/boards/board_title/board_title.dart
  lib/screens/boards/board_title/expanded_title_container.dart
  lib/screens/boards/board_title/unexpanded_title_container.dart
  lib/screens/boards/boards_app.dart
  lib/screens/boards/boards_body.dart
  lib/screens/boards/notice.dart
  lib/screens/boards/progress.dart
  lib/screens/boards/task.dart
  lib/screens/boards/tasks.dart
  lib/screens/boards/thread.dart
  lib/screens/boards/thread_page.dart
  lib/screens/boards/threads.dart
Labels: enhancement, server

#33 프로필 수정 페이지 디자인 및 API 붙이기
  assets/backgrounds/profile-bg-1.png
  assets/images/browser-icon.png
  assets/images/github-icon.png
  lib/screens/my_page/make_profile_page.dart
  lib/screens/my_page/my_page.dart
  lib/screens/my_page/my_profile.dart
  lib/screens/my_page/profile_filter_value_chip.dart
Labels: enhancement, server

#28 프로젝트 생성 디자인 및 API 붙이기
  lib/commons/page_status.dart
  lib/commons/project_create_container.dart
  lib/providers/projects/projects.dart
  lib/screens/projects/creation/project_create.dart
  lib/screens/projects/creation/project_create_button.dart
  lib/screens/projects/projects_app.dart
Labels: enhancement, server

#36 hotfix / 프로젝트 생성 시 400 에러 반환 문제 수정
  lib/screens/projects/creation/project_create.dart
Labels: server

#41 Thread / Comment POST w/ Image + pin notice + delete
  lib/commons/common_icon_button.dart
  lib/commons/common_text_field.dart
  lib/commons/image_thumbnail.dart
  lib/helpers/http_request.dart
  lib/helpers/pick_image.dart
  lib/models/boards/comment.dart
  lib/models/boards/thread.dart
  lib/models/boards/thread_comment_image.dart
  lib/models/boards/user_task.dart
  lib/models/project.dart
  lib/providers/boards/boards.dart
  lib/screens/boards/board.dart
  lib/screens/boards/bottom_modal/bottom_modal_content.dart
  lib/screens/boards/bottom_modal/function_container.dart
  lib/screens/boards/comment.dart
  lib/screens/boards/notice.dart
  lib/screens/boards/tasks.dart
  lib/screens/boards/thread.dart
  lib/screens/boards/thread_page.dart
  lib/screens/boards/thread_page/comment.dart
  lib/screens/boards/thread_page/comments_container.dart
  lib/screens/boards/thread_page/thread_comment_image_container.dart
  lib/screens/boards/thread_page/thread_comment_images.dart
  lib/screens/boards/thread_page/thread_container.dart
  lib/screens/boards/thread_page/thread_page.dart
  lib/screens/boards/threads.dart
  pubspec.lock
  pubspec.yaml
Labels: feature

#43 Feat/accept member
  lib/helpers/http_request.dart
  lib/models/project.dart
  lib/providers/boards/boards.dart
  lib/screens/boards/accept_decline_button.dart
  lib/screens/boards/tasks.dart
  lib/screens/boards/thread.dart
  lib/screens/boards/thread_page/thread_container.dart
  lib/screens/boards/thread_page/thread_page.dart
Labels: server

#37 Server/ 프로젝트 신청 API 연결 및 디자인 수정
  lib/models/profile.dart
  lib/models/project.dart
  lib/providers/projects/projects.dart
  lib/screens/projects/almost_full_projects_list.dart
  lib/screens/projects/detail/project_apply.dart
  lib/screens/projects/detail/project_detail.dart
  lib/screens/projects/detail/project_detail_apply.dart
  lib/screens/projects/detail/project_detail_body.dart
  lib/screens/projects/project_banner.dart
  lib/screens/projects/project_square.dart
  lib/screens/projects/projects_app.dart
  lib/screens/projects/projects_body.dart
  lib/screens/projects/projects_list.dart
  lib/screens/projects/search/projects_searched_list.dart
  pubspec.lock
  pubspec.yaml
Labels: enhancement, server

#44 [WIP] Fix/project create
  lib/commons/next_page.dart
  lib/commons/previous_page.dart
  lib/helpers/http_request.dart
  lib/helpers/translate.dart
  lib/models/project.dart
  lib/models/thumbnail.dart
  lib/providers/projects/projects.dart
  lib/screens/projects/creation/create_filter_chip.dart
  lib/screens/projects/creation/create_filter_value_chip.dart
  lib/screens/projects/creation/page_one/project_create_description.dart
  lib/screens/projects/creation/page_one/project_create_due.dart
  lib/screens/projects/creation/page_one/project_create_page_one.dart
  lib/screens/projects/creation/page_one/project_create_title.dart
  lib/screens/projects/creation/page_three/project_create_my_position.dart
  lib/screens/projects/creation/page_three/project_create_page_three.dart
  lib/screens/projects/creation/page_three/project_create_save.dart
  lib/screens/projects/creation/page_three/project_create_thumbnail.dart
  lib/screens/projects/creation/page_two/project_create_page_two.dart
  lib/screens/projects/creation/page_two/project_create_positions.dart
  lib/screens/projects/creation/project_create.dart
  lib/screens/projects/creation/project_create_button.dart
  lib/screens/projects/project_square.dart
  lib/screens/projects/projects_app.dart
Labels: enhancement, server

#45 Server/profile
  assets/backgrounds/profile-bg-1.png
  assets/images/project-thumbnail-default.png
  ios/Podfile.lock
  lib/commons/common_text_field.dart
  lib/commons/profile_thumbnail.dart
  lib/helpers/http_request.dart
  lib/helpers/pick_image.dart
  lib/models/profile.dart
  lib/providers/home/home_provider.dart
  lib/providers/user_auth/authenticate.dart
  lib/screens/boards/thread.dart
  lib/screens/my_page/make_profile_image.dart
  lib/screens/my_page/make_profile_page.dart
  lib/screens/my_page/my_page_app.dart
  lib/screens/my_page/my_profile.dart
  lib/screens/my_page/my_profile/my_profile.dart
  lib/screens/my_page/my_profile/my_profile_bottom.dart
  lib/screens/my_page/my_profile/my_profile_link.dart
  lib/screens/my_page/my_profile/my_profile_projects.dart
  lib/screens/my_page/my_profile/my_profile_top.dart
  lib/screens/my_page/profile_filter_value_chip.dart
  lib/screens/projects/detail/project_detail.dart
  lib/screens/projects/detail/project_detail_apply.dart
  pubspec.lock
  pubspec.yaml
Labels: enhancement, server
